#!/bin/sh
CIRCT_SRC_DIR=$PWD
INSTALL_PREFIX=$PWD/bin

export CIRCT_CMAKE_BUILD_DIR=$CIRCT_SRC_DIR/build
export CIRCT_LLVM_DIR=$CIRCT_SRC_DIR/llvm/llvm
export CMAKE_GENERATOR=Ninja
export CMAKE_C_COMPILER_LAUNCHER=ccache
export CMAKE_CXX_COMPILER_LAUNCHER=ccache

CIRCT_RELEASE_TAG=chipsorcery
PYTHON=OFF
cmake -B $CIRCT_CMAKE_BUILD_DIR -G $CMAKE_GENERATOR $CIRCT_LLVM_DIR \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DLLVM_TARGETS_TO_BUILD=host \
    -DLLVM_ENABLE_PROJECTS=mlir \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_EXTERNAL_PROJECTS=circt \
    -DLLVM_EXTERNAL_CIRCT_SOURCE_DIR=$CIRCT_SRC_DIR \
    -DLLVM_STATIC_LINK_CXX_STDLIB=ON \
    -DLLVM_OPTIMIZED_TABLEGEN=ON \
    -DLLVM_INSTALL_UTILS=OFF \
    -DMLIR_ENABLE_BINDINGS_PYTHON=$PYTHON \
    -DMLIR_INSTALL_AGGREGATE_OBJECTS=OFF \
    -DCIRCT_ENABLE_FRONTENDS=ON \
    -DCIRCT_INCLUDE_DOCS=OFF \
    -DCIRCT_BINDINGS_PYTHON_ENABLED=$PYTHON \
    -DCIRCT_RELEASE_TAG=$CIRCT_RELEASE_TAG \
    -DCIRCT_RELEASE_TAG_ENABLED=ON

cmake --build $CIRCT_CMAKE_BUILD_DIR --target install

#pip install $CIRCT_SRC_DIR/lib/Bindings/Python

